using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Stock
{

    private sbyte qtyField;

    private sbyte minQtyField;

    private sbyte maxQtyField;

    private sbyte onOrderQtyField;

    private sbyte receivedField;

    private sbyte priceField;

    /// <remarks/>
    public sbyte Qty
    {
        get
        {
            return this.qtyField;
        }
        set
        {
            this.qtyField = value;
        }
    }

    /// <remarks/>
    public sbyte MinQty
    {
        get
        {
            return this.minQtyField;
        }
        set
        {
            this.minQtyField = value;
        }
    }

    /// <remarks/>
    public sbyte MaxQty
    {
        get
        {
            return this.maxQtyField;
        }
        set
        {
            this.maxQtyField = value;
        }
    }

    /// <remarks/>
    public sbyte OnOrderQty
    {
        get
        {
            return this.onOrderQtyField;
        }
        set
        {
            this.onOrderQtyField = value;
        }
    }

    /// <remarks/>
    public sbyte Received
    {
        get
        {
            return this.receivedField;
        }
        set
        {
            this.receivedField = value;
        }
    }

    /// <remarks/>
    public sbyte Price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Tool
{

    private string guidField;

    private string libraryField;

    private string commentField;

    private string brand_nameField;

    private string series_nameField;

    private string supplierField;

    private string supplier_pidField;

    private System.DateTime create_dateField;

    private System.DateTime update_dateField;

    private Stock stockField;

    private sbyte idField;

    private sbyte user_idField;

    private string typeField;

    private sbyte maxdeflection_pcField;

    private sbyte maxtorque_pcField;

    private sbyte productivityField;

    private sbyte thread_drill_diaField;

    private sbyte thread_drill_dia_mField;

    private sbyte custom_SFField;

    private sbyte genericField;

    private sbyte offset_DiameterField;

    private sbyte offset_LengthField;

    private sbyte coolantField;

    private sbyte isInsertField;

    private sbyte numberField;

    private float diameterField;

    private float stickoutField;

    private float corner_radField;

    private sbyte instockField;

    private sbyte stockOrderQtyField;

    private sbyte stockMinQtyField;

    private sbyte stockMaxQtyField;

    private sbyte stockOnOrderQtyField;

    private sbyte stockReceivedField;

    private sbyte stockPriceField;

    private sbyte tool_lifeField;

    private sbyte ratingField;

    private float shank_DiaField;

    private sbyte flute_NField;

    private float flute_LenField;

    private float shoulder_LenField;

    private float shoulder_DiaField;

    private sbyte shoulder_TaperedField;

    private sbyte helix_angleField;

    private sbyte leadangleField;

    private sbyte leadangle_modeField;

    private sbyte tool_material_idField;

    private sbyte name_idField;

    private sbyte coating_idField;

    private sbyte rampmillingField;

    private sbyte rampField;

    private sbyte peckField;

    private float docField;

    private float wocField;

    private sbyte sfm_adjField;

    private sbyte ipt_adjField;

    private sbyte tool_maxrpmField;

    private sbyte depthField;

    private sbyte circle_compField;

    private sbyte hsmField;

    private sbyte hssField;

    private sbyte circle_diaField;

    private sbyte circle_externalField;

    private sbyte thread_pitchField;

    private sbyte pilot_HoleField;

    private sbyte diameter_mmField;

    private sbyte shank_Dia_mmField;

    private sbyte flute_len_mmField;

    private sbyte stickout_mmField;

    private sbyte corner_rad_mmField;

    private sbyte doc_mmField;

    private sbyte woc_mmField;

    private sbyte ipt_mmField;

    private sbyte sfm_mmField;

    private sbyte feed_mmField;

    private sbyte input_units_mmField;

    private sbyte result_units_mmField;

    private sbyte circle_dia_mmField;

    private sbyte depth_mmField;

    private sbyte shoulder_len_mmField;

    private sbyte peck_mmField;

    private sbyte thread_pitch_mField;

    private sbyte shoulder_Dia_mmField;

    private sbyte pilot_Hole_mmField;

    private string cutsField;

    /// <remarks/>
    public string guid
    {
        get
        {
            return this.guidField;
        }
        set
        {
            this.guidField = value;
        }
    }

    /// <remarks/>
    public string library
    {
        get
        {
            return this.libraryField;
        }
        set
        {
            this.libraryField = value;
        }
    }

    /// <remarks/>
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }

    /// <remarks/>
    public string brand_name
    {
        get
        {
            return this.brand_nameField;
        }
        set
        {
            this.brand_nameField = value;
        }
    }

    /// <remarks/>
    public string series_name
    {
        get
        {
            return this.series_nameField;
        }
        set
        {
            this.series_nameField = value;
        }
    }

    /// <remarks/>
    public string supplier
    {
        get
        {
            return this.supplierField;
        }
        set
        {
            this.supplierField = value;
        }
    }

    /// <remarks/>
    public string supplier_pid
    {
        get
        {
            return this.supplier_pidField;
        }
        set
        {
            this.supplier_pidField = value;
        }
    }

    /// <remarks/>
    public System.DateTime create_date
    {
        get
        {
            return this.create_dateField;
        }
        set
        {
            this.create_dateField = value;
        }
    }

    /// <remarks/>
    public System.DateTime update_date
    {
        get
        {
            return this.update_dateField;
        }
        set
        {
            this.update_dateField = value;
        }
    }

    /// <remarks/>
    public Stock Stock
    {
        get
        {
            return this.stockField;
        }
        set
        {
            this.stockField = value;
        }
    }

    /// <remarks/>
    public sbyte id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    public sbyte user_id
    {
        get
        {
            return this.user_idField;
        }
        set
        {
            this.user_idField = value;
        }
    }

    /// <remarks/>
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public sbyte maxdeflection_pc
    {
        get
        {
            return this.maxdeflection_pcField;
        }
        set
        {
            this.maxdeflection_pcField = value;
        }
    }

    /// <remarks/>
    public sbyte maxtorque_pc
    {
        get
        {
            return this.maxtorque_pcField;
        }
        set
        {
            this.maxtorque_pcField = value;
        }
    }

    /// <remarks/>
    public sbyte productivity
    {
        get
        {
            return this.productivityField;
        }
        set
        {
            this.productivityField = value;
        }
    }

    /// <remarks/>
    public sbyte thread_drill_dia
    {
        get
        {
            return this.thread_drill_diaField;
        }
        set
        {
            this.thread_drill_diaField = value;
        }
    }

    /// <remarks/>
    public sbyte thread_drill_dia_m
    {
        get
        {
            return this.thread_drill_dia_mField;
        }
        set
        {
            this.thread_drill_dia_mField = value;
        }
    }

    /// <remarks/>
    public sbyte custom_SF
    {
        get
        {
            return this.custom_SFField;
        }
        set
        {
            this.custom_SFField = value;
        }
    }

    /// <remarks/>
    public sbyte generic
    {
        get
        {
            return this.genericField;
        }
        set
        {
            this.genericField = value;
        }
    }

    /// <remarks/>
    public sbyte Offset_Diameter
    {
        get
        {
            return this.offset_DiameterField;
        }
        set
        {
            this.offset_DiameterField = value;
        }
    }

    /// <remarks/>
    public sbyte Offset_Length
    {
        get
        {
            return this.offset_LengthField;
        }
        set
        {
            this.offset_LengthField = value;
        }
    }

    /// <remarks/>
    public sbyte Coolant
    {
        get
        {
            return this.coolantField;
        }
        set
        {
            this.coolantField = value;
        }
    }

    /// <remarks/>
    public sbyte isInsert
    {
        get
        {
            return this.isInsertField;
        }
        set
        {
            this.isInsertField = value;
        }
    }

    /// <remarks/>
    public sbyte number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    public float diameter
    {
        get
        {
            return this.diameterField;
        }
        set
        {
            this.diameterField = value;
        }
    }

    /// <remarks/>
    public float stickout
    {
        get
        {
            return this.stickoutField;
        }
        set
        {
            this.stickoutField = value;
        }
    }

    /// <remarks/>
    public float corner_rad
    {
        get
        {
            return this.corner_radField;
        }
        set
        {
            this.corner_radField = value;
        }
    }

    /// <remarks/>
    public sbyte instock
    {
        get
        {
            return this.instockField;
        }
        set
        {
            this.instockField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.OrderQty")]
    public sbyte stockOrderQty
    {
        get
        {
            return this.stockOrderQtyField;
        }
        set
        {
            this.stockOrderQtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.MinQty")]
    public sbyte stockMinQty
    {
        get
        {
            return this.stockMinQtyField;
        }
        set
        {
            this.stockMinQtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.MaxQty")]
    public sbyte stockMaxQty
    {
        get
        {
            return this.stockMaxQtyField;
        }
        set
        {
            this.stockMaxQtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.OnOrderQty")]
    public sbyte stockOnOrderQty
    {
        get
        {
            return this.stockOnOrderQtyField;
        }
        set
        {
            this.stockOnOrderQtyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.Received")]
    public sbyte stockReceived
    {
        get
        {
            return this.stockReceivedField;
        }
        set
        {
            this.stockReceivedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stock.Price")]
    public sbyte stockPrice
    {
        get
        {
            return this.stockPriceField;
        }
        set
        {
            this.stockPriceField = value;
        }
    }

    /// <remarks/>
    public sbyte tool_life
    {
        get
        {
            return this.tool_lifeField;
        }
        set
        {
            this.tool_lifeField = value;
        }
    }

    /// <remarks/>
    public sbyte rating
    {
        get
        {
            return this.ratingField;
        }
        set
        {
            this.ratingField = value;
        }
    }

    /// <remarks/>
    public float Shank_Dia
    {
        get
        {
            return this.shank_DiaField;
        }
        set
        {
            this.shank_DiaField = value;
        }
    }

    /// <remarks/>
    public sbyte Flute_N
    {
        get
        {
            return this.flute_NField;
        }
        set
        {
            this.flute_NField = value;
        }
    }

    /// <remarks/>
    public float Flute_Len
    {
        get
        {
            return this.flute_LenField;
        }
        set
        {
            this.flute_LenField = value;
        }
    }

    /// <remarks/>
    public float Shoulder_Len
    {
        get
        {
            return this.shoulder_LenField;
        }
        set
        {
            this.shoulder_LenField = value;
        }
    }

    /// <remarks/>
    public float Shoulder_Dia
    {
        get
        {
            return this.shoulder_DiaField;
        }
        set
        {
            this.shoulder_DiaField = value;
        }
    }

    /// <remarks/>
    public sbyte Shoulder_Tapered
    {
        get
        {
            return this.shoulder_TaperedField;
        }
        set
        {
            this.shoulder_TaperedField = value;
        }
    }

    /// <remarks/>
    public sbyte helix_angle
    {
        get
        {
            return this.helix_angleField;
        }
        set
        {
            this.helix_angleField = value;
        }
    }

    /// <remarks/>
    public sbyte leadangle
    {
        get
        {
            return this.leadangleField;
        }
        set
        {
            this.leadangleField = value;
        }
    }

    /// <remarks/>
    public sbyte leadangle_mode
    {
        get
        {
            return this.leadangle_modeField;
        }
        set
        {
            this.leadangle_modeField = value;
        }
    }

    /// <remarks/>
    public sbyte tool_material_id
    {
        get
        {
            return this.tool_material_idField;
        }
        set
        {
            this.tool_material_idField = value;
        }
    }

    /// <remarks/>
    public sbyte name_id
    {
        get
        {
            return this.name_idField;
        }
        set
        {
            this.name_idField = value;
        }
    }

    /// <remarks/>
    public sbyte coating_id
    {
        get
        {
            return this.coating_idField;
        }
        set
        {
            this.coating_idField = value;
        }
    }

    /// <remarks/>
    public sbyte rampmilling
    {
        get
        {
            return this.rampmillingField;
        }
        set
        {
            this.rampmillingField = value;
        }
    }

    /// <remarks/>
    public sbyte ramp
    {
        get
        {
            return this.rampField;
        }
        set
        {
            this.rampField = value;
        }
    }

    /// <remarks/>
    public sbyte peck
    {
        get
        {
            return this.peckField;
        }
        set
        {
            this.peckField = value;
        }
    }

    /// <remarks/>
    public float doc
    {
        get
        {
            return this.docField;
        }
        set
        {
            this.docField = value;
        }
    }

    /// <remarks/>
    public float woc
    {
        get
        {
            return this.wocField;
        }
        set
        {
            this.wocField = value;
        }
    }

    /// <remarks/>
    public sbyte sfm_adj
    {
        get
        {
            return this.sfm_adjField;
        }
        set
        {
            this.sfm_adjField = value;
        }
    }

    /// <remarks/>
    public sbyte ipt_adj
    {
        get
        {
            return this.ipt_adjField;
        }
        set
        {
            this.ipt_adjField = value;
        }
    }

    /// <remarks/>
    public sbyte tool_maxrpm
    {
        get
        {
            return this.tool_maxrpmField;
        }
        set
        {
            this.tool_maxrpmField = value;
        }
    }

    /// <remarks/>
    public sbyte depth
    {
        get
        {
            return this.depthField;
        }
        set
        {
            this.depthField = value;
        }
    }

    /// <remarks/>
    public sbyte circle_comp
    {
        get
        {
            return this.circle_compField;
        }
        set
        {
            this.circle_compField = value;
        }
    }

    /// <remarks/>
    public sbyte hsm
    {
        get
        {
            return this.hsmField;
        }
        set
        {
            this.hsmField = value;
        }
    }

    /// <remarks/>
    public sbyte hss
    {
        get
        {
            return this.hssField;
        }
        set
        {
            this.hssField = value;
        }
    }

    /// <remarks/>
    public sbyte circle_dia
    {
        get
        {
            return this.circle_diaField;
        }
        set
        {
            this.circle_diaField = value;
        }
    }

    /// <remarks/>
    public sbyte circle_external
    {
        get
        {
            return this.circle_externalField;
        }
        set
        {
            this.circle_externalField = value;
        }
    }

    /// <remarks/>
    public sbyte thread_pitch
    {
        get
        {
            return this.thread_pitchField;
        }
        set
        {
            this.thread_pitchField = value;
        }
    }

    /// <remarks/>
    public sbyte Pilot_Hole
    {
        get
        {
            return this.pilot_HoleField;
        }
        set
        {
            this.pilot_HoleField = value;
        }
    }

    /// <remarks/>
    public sbyte diameter_mm
    {
        get
        {
            return this.diameter_mmField;
        }
        set
        {
            this.diameter_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte Shank_Dia_mm
    {
        get
        {
            return this.shank_Dia_mmField;
        }
        set
        {
            this.shank_Dia_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte flute_len_mm
    {
        get
        {
            return this.flute_len_mmField;
        }
        set
        {
            this.flute_len_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte stickout_mm
    {
        get
        {
            return this.stickout_mmField;
        }
        set
        {
            this.stickout_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte corner_rad_mm
    {
        get
        {
            return this.corner_rad_mmField;
        }
        set
        {
            this.corner_rad_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte doc_mm
    {
        get
        {
            return this.doc_mmField;
        }
        set
        {
            this.doc_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte woc_mm
    {
        get
        {
            return this.woc_mmField;
        }
        set
        {
            this.woc_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte ipt_mm
    {
        get
        {
            return this.ipt_mmField;
        }
        set
        {
            this.ipt_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte sfm_mm
    {
        get
        {
            return this.sfm_mmField;
        }
        set
        {
            this.sfm_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte feed_mm
    {
        get
        {
            return this.feed_mmField;
        }
        set
        {
            this.feed_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte input_units_mm
    {
        get
        {
            return this.input_units_mmField;
        }
        set
        {
            this.input_units_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte result_units_mm
    {
        get
        {
            return this.result_units_mmField;
        }
        set
        {
            this.result_units_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte circle_dia_mm
    {
        get
        {
            return this.circle_dia_mmField;
        }
        set
        {
            this.circle_dia_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte depth_mm
    {
        get
        {
            return this.depth_mmField;
        }
        set
        {
            this.depth_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte shoulder_len_mm
    {
        get
        {
            return this.shoulder_len_mmField;
        }
        set
        {
            this.shoulder_len_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte peck_mm
    {
        get
        {
            return this.peck_mmField;
        }
        set
        {
            this.peck_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte thread_pitch_m
    {
        get
        {
            return this.thread_pitch_mField;
        }
        set
        {
            this.thread_pitch_mField = value;
        }
    }

    /// <remarks/>
    public sbyte Shoulder_Dia_mm
    {
        get
        {
            return this.shoulder_Dia_mmField;
        }
        set
        {
            this.shoulder_Dia_mmField = value;
        }
    }

    /// <remarks/>
    public sbyte Pilot_Hole_mm
    {
        get
        {
            return this.pilot_Hole_mmField;
        }
        set
        {
            this.pilot_Hole_mmField = value;
        }
    }

    /// <remarks/>
    public string Cuts
    {
        get
        {
            return this.cutsField;
        }
        set
        {
            this.cutsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Library
{

    private string nameField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Tools
{

    private Tool[] toolField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tool")]
    public Tool[] Tool
    {
        get
        {
            return this.toolField;
        }
        set
        {
            this.toolField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Libraries
{

    private Library libraryField;

    /// <remarks/>
    public Library Library
    {
        get
        {
            return this.libraryField;
        }
        set
        {
            this.libraryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class settings
{

    private string dB_SharedField;

    /// <remarks/>
    public string DB_Shared
    {
        get
        {
            return this.dB_SharedField;
        }
        set
        {
            this.dB_SharedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class DataBase
{

    private Tool[] toolsField;

    private Libraries librariesField;

    private string customSFMsField;

    private string toolRequestsField;

    private settings settingsField;

    private string holdersField;

    private string machineInterfacesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tool", IsNullable = false)]
    public Tool[] Tools
    {
        get
        {
            return this.toolsField;
        }
        set
        {
            this.toolsField = value;
        }
    }

    /// <remarks/>
    public Libraries Libraries
    {
        get
        {
            return this.librariesField;
        }
        set
        {
            this.librariesField = value;
        }
    }

    /// <remarks/>
    public string CustomSFMs
    {
        get
        {
            return this.customSFMsField;
        }
        set
        {
            this.customSFMsField = value;
        }
    }

    /// <remarks/>
    public string ToolRequests
    {
        get
        {
            return this.toolRequestsField;
        }
        set
        {
            this.toolRequestsField = value;
        }
    }

    /// <remarks/>
    public settings settings
    {
        get
        {
            return this.settingsField;
        }
        set
        {
            this.settingsField = value;
        }
    }

    /// <remarks/>
    public string Holders
    {
        get
        {
            return this.holdersField;
        }
        set
        {
            this.holdersField = value;
        }
    }

    /// <remarks/>
    public string MachineInterfaces
    {
        get
        {
            return this.machineInterfacesField;
        }
        set
        {
            this.machineInterfacesField = value;
        }
    }
}
